import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {checkFigureHistory} from './figure-history.mjs';
const root=resolve('dist/app');
const server=createServer(async(req,res)=>{try{const file=resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/\/$/,'/index.html'));if(!file.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.json':'application/json','.geojson':'application/json','.html':'text/html','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream');res.end(await readFile(file));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const manifest=JSON.parse(await readFile(resolve(root,'data/figures/current.json'),'utf8'));
 const frozen=JSON.parse(await readFile(resolve(root,`data/figures/${manifest.figure_id}.json`),'utf8'));
 await checkFigureHistory(browser,base,manifest,frozen);
 const expected=frozen.evidence.protection_estimates.find(e=>e.geography_id==='manhattan'&&e.population_id==='public_housing').value;
 // Current fixture files can differ after the repository's normalization tests; serve a coherent release.
 await page.route('**/data/nychvs/estimates.json',route=>route.fulfill({json:frozen.evidence}));
 await page.goto(base+'/');await page.locator('[data-testid=protection-gap]').waitFor();
 assert.equal(await page.locator('[data-group=public_housing]').innerText(),new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(expected));
 await page.click('#figure-link');await page.locator('.figure-version').waitFor();
 const url=page.url();assert.equal(new URL(url).searchParams.get('figure'),manifest.figure_id);
 const before=await page.locator('.protection-bars').innerText();
 await page.unroute('**/data/nychvs/estimates.json');
 const changed=structuredClone(frozen.evidence);changed.protection_estimates.forEach(e=>e.value=9999);
 await page.route('**/data/nychvs/estimates.json',route=>route.fulfill({json:changed}));
 await page.goto(url);await page.locator('.figure-version').waitFor();assert.equal(await page.locator('.protection-bars').innerText(),before);
 assert.equal(await page.locator('.protection-evidence a').last().getAttribute('href'),`data/figures/${manifest.figure_id}.json`);
 const event=page.waitForEvent('download');await page.click('#figure-svg');const dl=await event;const svg=await readFile(await dl.path(),'utf8');
 assert.ok(svg.includes(String(expected)));assert.ok(svg.includes('NYC HPD'));assert.ok(svg.includes('MIT'));assert.ok(svg.includes(manifest.figure_id));
 await writeFile('/tmp/nycrs-final-figure.svg',svg);
 const imagePage=await browser.newPage();await imagePage.setContent(svg);await imagePage.screenshot({path:'/tmp/nycrs-final-figure.png',fullPage:true});await imagePage.close();
 const download=page.waitForEvent('download');await page.click('#protection-download');const exact=JSON.parse(await readFile(await (await download).path(),'utf8'));assert.equal(exact.figure_id,manifest.figure_id);assert.equal(exact.estimates.find(e=>e.population_id==='public_housing').value,expected);
 await page.evaluate(()=>{window.print=()=>{window.printDetails=[...document.querySelectorAll('#protection-host details')].map(e=>e.open);};});
 await page.click('#figure-print');assert.ok(await page.evaluate(()=>window.printDetails?.length>0&&window.printDetails.every(Boolean)));assert.equal(await page.locator('details.protection-evidence').evaluate(el=>el.open),false);
 await page.screenshot({path:'/tmp/nycrs-final-rents.png',fullPage:true});
 await page.click('[data-analysis=space]');await page.locator('.space-matrix').waitFor();
 const spaceEvent=page.waitForEvent('download');await page.click('#figure-svg');const spaceSvg=await readFile(await (await spaceEvent).path(),'utf8');assert.ok(spaceSvg.includes('15.0%'));assert.ok(spaceSvg.includes('5.1%'));assert.ok(spaceSvg.includes('5.8%'));
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/nycrs-final-space-mobile.png',fullPage:true});
 await page.goto(base+'/?view=protection&analysis=access&against=unmapped-program&figure='+manifest.figure_id);
 await page.getByText('No single allocation rule is assigned',{exact:false}).waitFor();await page.click('#figure-link');await page.reload();await page.getByText('No single allocation rule is assigned',{exact:false}).waitFor();
 assert.equal(new URL(page.url()).searchParams.get('accessGroup'),'unmapped-program');
 await page.goto(base+'/?view=protection&figure='+'0'.repeat(64));await page.getByRole('alert').waitFor();assert.equal(await page.locator('.protection-bars').count(),0);
 await page.goto(base+'/?view=protection&figure=invalid');await page.getByRole('alert').waitFor();
 await page.route('**/data/figures/'+manifest.figure_id+'.json',route=>route.fulfill({body:'{}',contentType:'application/json'}));
 await page.goto(url);await page.getByRole('alert').waitFor();await page.unroute('**/data/figures/'+manifest.figure_id+'.json');
 await page.goto(base+'/?view=protection');await page.locator('#figure-link').waitFor();await page.click('#figure-link');await page.getByText('A matching citable release is unavailable.',{exact:false}).waitFor();assert.equal(new URL(page.url()).searchParams.has('figure'),false);
 await page.goto(base+'/?development=nycha:tds:136');await page.locator('#protection-host[hidden]').waitFor({state:'attached'});
 await page.goto(base+'/?view=protection&against=unknown');await page.locator('#protection-against').waitFor();assert.equal(await page.locator('#protection-against').inputValue(),'unknown');
 console.log('Frozen figures: exact values, changed-current isolation, immutable links, SVG, print, downloads, invalid versions, mobile and legacy links passed');
}finally{await browser.close();await new Promise(r=>server.close(r));}
