import {escapeHtml as esc} from '../format';
export interface SpaceCell {people:string; bedrooms:string; available:boolean; share:number|null; weighted_households:number|null; sample_count:number; confidence_interval_lower:number|null; confidence_interval_upper:number|null; reliability_status:string; none_observed?:boolean; caveats?:string[]; publication_policy_version?:number; unavailable_reason?:string|null;}
export interface SpaceDistribution {population_id:string; population_label:string; geography_id:string; geography_name:string; sample_count:number; weighted_households:number|null; missing_dimensions_sample_count:number; missing_dimensions_weighted_households:number|null; invalid_weight_sample_count:number; cells:SpaceCell[];}
export interface SpaceEvidence {survey_vintage:string; denominator:string; distributions:SpaceDistribution[];}
const pct=(v:number|null|undefined)=>v==null?'Unavailable':`${(v*100).toFixed(1)}%`;
const count=(v:number|null)=>v==null?'Unavailable':Math.round(v).toLocaleString('en-US');
const cellLabel=(c:SpaceCell|undefined)=>c?.none_observed?'None observed in this sample':pct(c?.share);
export function spaceNote(c:SpaceCell|undefined,d:SpaceDistribution):string {
 if(!c)return 'Cell unavailable.';
 const counts=`${c.sample_count} cell responses / ${d.sample_count} group responses; ${count(d.weighted_households)} weighted group households.`;
 if(!c.available)return `${counts} Unavailable: ${c.unavailable_reason?.replaceAll('_',' ')||'withheld under this saved policy'}.`;
 if(c.none_observed)return `${counts} None observed in this sample; not evidence of population absence. No interval is asserted.`;
 const interval=c.confidence_interval_lower!=null&&c.confidence_interval_upper!=null?`95% interval: ${pct(c.confidence_interval_lower)}–${pct(c.confidence_interval_upper)}.`:'Uncertainty could not be estimated';
 return [counts,...(c.caveats||[]).filter(v=>v!=='Uncertainty could not be estimated'),interval].join(' ');
}
export function spaceSelection(data:SpaceEvidence,params:URLSearchParams){
 const geographies=Object.fromEntries(data.distributions.map(d=>[d.geography_id,d.geography_name]));
 const groups=Object.fromEntries(data.distributions.map(d=>[d.population_id,d.population_label]));
 const geo=Object.keys(geographies).find(id=>id===params.get('spaceGeo'))||'nyc';
 const group=Object.keys(groups).find(id=>id===params.get('spaceGroup'))||'public_housing';
 const people=['1','2','3','4+'].find(id=>id===params.get('people'))||'1';
 const bedrooms=['0','1','2','3','4+'].find(id=>id===params.get('bedrooms'))||'2';
 const distribution=data.distributions.find(d=>d.geography_id===geo&&d.population_id===group);
 const comparisons=data.distributions.filter(d=>d.geography_id===geo).map(d=>({...d,cells:d.cells.filter(c=>c.people===people&&c.bedrooms===bedrooms)}));
 return {geo,group,people,bedrooms,distribution,comparisons,geographies,groups};
}
export function renderHouseholdSpace(data:SpaceEvidence|undefined,params:URLSearchParams,source:string):string{
 if(!data)return '<p>Household-space evidence is unavailable for this release.</p>';
 const s=spaceSelection(data,params), d=s.distribution;
 if(!d)return '<p>This distribution is unavailable.</p>';
 const options=(items:Record<string,string>,selected:string)=>Object.entries(items).map(([id,label])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(label)}</option>`).join('');
 const title=`${s.people} ${s.people==='1'?'person':'people'} · ${s.bedrooms==='0'?'studio':`${s.bedrooms} bedrooms`}`;
 const chosen=d.cells.find(c=>c.people===s.people&&c.bedrooms===s.bedrooms);
 return `<div class="protection-controls"><label>Geography <select id="space-geography" data-space-key="spaceGeo">${options(s.geographies,s.geo)}</select></label><label>Housing group <select id="space-group" data-space-key="spaceGroup">${options(s.groups,s.group)}</select></label></div>
 <div class="space-grid"><section><h3>${esc(d.population_label)} · ${esc(d.geography_name)}</h3><p class="muted">Share of households by people and bedrooms</p><div class="protection-table"><table class="space-matrix"><caption>Bedrooms →</caption><thead><tr><th>People ↓</th>${['0','1','2','3','4+'].map(b=>`<th>${b==='0'?'Studio':b}</th>`).join('')}</tr></thead><tbody>${['1','2','3','4+'].map(p=>`<tr><th scope="row">${p}</th>${['0','1','2','3','4+'].map(b=>{const c=d.cells.find(c=>c.people===p&&c.bedrooms===b);return `<td><button data-space-cell="${p},${b}" data-focus="space-${p}-${b}" aria-pressed="${p===s.people&&b===s.bedrooms}" aria-label="${p} people, ${b==='0'?'studio':b+' bedrooms'}: ${esc(cellLabel(c))}. ${esc(spaceNote(c,d))}" style="--cell-opacity:${c?.available ? .12+(c.share||0)*2:0}">${c?.none_observed?'None observed':c?.available?pct(c.share):'—'}<small>n=${c?.sample_count??0}</small></button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div><p class="muted">— Estimate unavailable · None observed means none in this sample, not population absence · n = cell responses · 4+ combines larger categories</p><p class="space-denominator">${count(d.weighted_households)} weighted households · ${d.sample_count.toLocaleString()} survey responses</p></section>
 <section><h3>${esc(title)}</h3><p class="muted">As a share of each housing group · ${esc(d.geography_name)}</p><div class="protection-bars">${s.comparisons.filter(e=>['public_housing','rent_stabilized','unassisted_market',s.group].includes(e.population_id)).map(e=>{const c=e.cells[0];return `<div class="protection-bar"><div><span>${esc(e.population_label)}</span><b data-space-group="${e.population_id}">${esc(cellLabel(c))}</b></div><div class="protection-track"><i style="width:${(c?.share||0)*100}%;background:${e.population_id==='public_housing'?'var(--nycha)':e.population_id==='unassisted_market'?'var(--market)':'var(--wedge)'}"></i></div><p class="uncertainty-note">${esc(spaceNote(c,e))}</p></div>`;}).join('')}</div><p class="space-cell-detail" data-testid="space-detail">${esc(cellLabel(chosen))} · ${esc(spaceNote(chosen,d))}</p></section></div>
 <button class="btn contextual-access" data-focus="access-origin-space" data-open-access="${esc(s.group)}">Program details</button>
 <details class="protection-evidence"><summary>Denominators, exact values and source</summary><p>${esc(data.denominator)}</p><div class="protection-table"><table><thead><tr><th>Group</th><th>Selected share</th><th>95% interval</th><th>Cell sample</th><th>Weighted denominator</th><th>Missing dimensions</th><th>Status</th></tr></thead><tbody>${s.comparisons.map(e=>{const c=e.cells[0];return `<tr><td>${esc(e.population_label)}</td><td>${esc(cellLabel(c))}</td><td>${c.available?pct(c.confidence_interval_lower)+'–'+pct(c.confidence_interval_upper):'—'}</td><td>${c.sample_count}</td><td>${count(e.weighted_households)}</td><td>${e.missing_dimensions_sample_count} responses / ${count(e.missing_dimensions_weighted_households)} weighted</td><td>${esc(c.reliability_status.replaceAll('_',' '))}</td></tr>`;}).join('')}</tbody></table></div><p>2023 NYCHVS HHSIZE (occupied households) joined to BEDROOMS (all units) by CONTROL. Positive survey weights; 80 replicate weights for uncertainty. ${d.cells.some(c=>c.publication_policy_version===2)?'Shares use their own publication rules: valid values remain visible regardless of cell size or CV. Sample counts, group denominators and valid intervals qualify precision. None observed does not establish population absence; no zero-width interval is published for an unobserved cell.':'This saved policy withheld small or high-uncertainty cells; unavailable cells are not zero.'} Household size and bedrooms describe occupied space, not individual eligibility or transfer decisions.</p><p><a href="${esc(source)}">HPD codebook, pages 22 and 40</a> · <a href="data/nychvs/estimates.json">Complete distributions and checksums</a></p></details>`;
}
