import {escapeHtml as esc} from '../format';
export interface SpaceCell {people:string; bedrooms:string; available:boolean; share:number|null; weighted_households:number|null; sample_count:number; confidence_interval_lower:number|null; confidence_interval_upper:number|null; reliability_status:string;}
export interface SpaceDistribution {population_id:string; population_label:string; geography_id:string; geography_name:string; sample_count:number; weighted_households:number; missing_dimensions_sample_count:number; missing_dimensions_weighted_households:number; invalid_weight_sample_count:number; cells:SpaceCell[];}
export interface SpaceEvidence {survey_vintage:string; denominator:string; distributions:SpaceDistribution[];}
const pct=(v:number|null|undefined)=>v==null?'Unavailable':`${(v*100).toFixed(1)}%`;
const count=(v:number)=>Math.round(v).toLocaleString('en-US');
export function spaceSelection(data:SpaceEvidence,params:URLSearchParams){
 const geographies=Object.fromEntries(data.distributions.map(d=>[d.geography_id,d.geography_name]));
 const groups=Object.fromEntries(data.distributions.map(d=>[d.population_id,d.population_label]));
 const geo=Object.keys(geographies).find(id=>id===params.get('spaceGeo'))||'nyc';
 const group=Object.keys(groups).find(id=>id===params.get('spaceGroup'))||'public_housing';
 const people=['1','2','3','4+'].find(id=>id===params.get('people'))||'1';
 const bedrooms=['0','1','2','3','4+'].find(id=>id===params.get('bedrooms'))||'2';
 const distribution=data.distributions.find(d=>d.geography_id===geo&&d.population_id===group);
 const comparisons=data.distributions.filter(d=>d.geography_id===geo).map(d=>({...d,cells:d.cells.filter(c=>c.people===people&&c.bedrooms===bedrooms)}));
 return {geo,group,people,bedrooms,distribution,comparisons,geographies,groups};
}
export function renderHouseholdSpace(data:SpaceEvidence|undefined,params:URLSearchParams,source:string):string{
 if(!data)return '<p>Household-space evidence is unavailable for this release.</p>';
 const s=spaceSelection(data,params), d=s.distribution;
 if(!d)return '<p>This distribution is unavailable.</p>';
 const options=(items:Record<string,string>,selected:string)=>Object.entries(items).map(([id,label])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(label)}</option>`).join('');
 const title=`${s.people} ${s.people==='1'?'person':'people'} · ${s.bedrooms==='0'?'studio':`${s.bedrooms} bedrooms`}`;
 const chosen=d.cells.find(c=>c.people===s.people&&c.bedrooms===s.bedrooms);
 return `<div class="protection-controls"><label>Geography <select id="space-geography" data-space-key="spaceGeo">${options(s.geographies,s.geo)}</select></label><label>Housing group <select id="space-group" data-space-key="spaceGroup">${options(s.groups,s.group)}</select></label></div>
 <div class="space-grid"><section><h3>${esc(d.population_label)} · ${esc(d.geography_name)}</h3><p class="muted">Share of households by people and bedrooms</p><div class="protection-table"><table class="space-matrix"><caption>Bedrooms →</caption><thead><tr><th>People ↓</th>${['0','1','2','3','4+'].map(b=>`<th>${b==='0'?'Studio':b}</th>`).join('')}</tr></thead><tbody>${['1','2','3','4+'].map(p=>`<tr><th scope="row">${p}</th>${['0','1','2','3','4+'].map(b=>{const c=d.cells.find(c=>c.people===p&&c.bedrooms===b);return `<td><button data-space-cell="${p},${b}" data-focus="space-${p}-${b}" aria-pressed="${p===s.people&&b===s.bedrooms}" aria-label="${p} people, ${b==='0'?'studio':b+' bedrooms'}: ${pct(c?.share)}" style="--cell-opacity:${c?.available ? .12+(c.share||0)*2:0}">${c?.available?pct(c.share):'—'}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div><p class="muted">— Estimate unavailable · 4+ combines larger categories</p><p class="space-denominator">${count(d.weighted_households)} weighted households · ${d.sample_count.toLocaleString()} survey responses</p></section>
 <section><h3>${esc(title)}</h3><p class="muted">As a share of each housing group · ${esc(d.geography_name)}</p><div class="protection-bars">${s.comparisons.filter(e=>['public_housing','rent_stabilized','unassisted_market',s.group].includes(e.population_id)).map(e=>{const c=e.cells[0];return `<div class="protection-bar"><div><span>${esc(e.population_label)}</span><b data-space-group="${e.population_id}">${pct(c?.share)}</b></div><div class="protection-track"><i style="width:${(c?.share||0)*100}%;background:${e.population_id==='public_housing'?'var(--nycha)':e.population_id==='unassisted_market'?'var(--market)':'var(--wedge)'}"></i></div></div>`;}).join('')}</div><p class="space-cell-detail" data-testid="space-detail">${chosen?.available?`${pct(chosen.share)} of ${esc(d.population_label.toLowerCase())} households · 95% interval ${pct(chosen.confidence_interval_lower)}–${pct(chosen.confidence_interval_upper)}`:'This cell has insufficient sample support.'}</p></section></div>
 <button class="btn contextual-access" data-open-access="${esc(s.group)}">Who controls access?</button>
 <details class="protection-evidence"><summary>Denominators, exact values and source</summary><p>${esc(data.denominator)}</p><div class="protection-table"><table><thead><tr><th>Group</th><th>Selected share</th><th>95% interval</th><th>Cell sample</th><th>Weighted denominator</th><th>Missing dimensions</th><th>Status</th></tr></thead><tbody>${s.comparisons.map(e=>{const c=e.cells[0];return `<tr><td>${esc(e.population_label)}</td><td>${pct(c.share)}</td><td>${c.available?pct(c.confidence_interval_lower)+'–'+pct(c.confidence_interval_upper):'—'}</td><td>${c.sample_count}</td><td>${count(e.weighted_households)}</td><td>${e.missing_dimensions_sample_count} responses / ${count(e.missing_dimensions_weighted_households)} weighted</td><td>${esc(c.reliability_status.replaceAll('_',' '))}</td></tr>`;}).join('')}</tbody></table></div><p>2023 NYCHVS HHSIZE (occupied households) joined to BEDROOMS (all units) by CONTROL. Positive survey weights; 80 replicate weights for uncertainty. Cells below 30 responses or above the project’s uncertainty limit are unavailable; hidden cells are not zero. Household size and bedrooms describe occupied space, not individual eligibility or transfer decisions.</p><p><a href="${esc(source)}">HPD codebook, pages 22 and 40</a> · <a href="data/nychvs/estimates.json">Complete distributions and checksums</a></p></details>`;
}
